package core

import (
	"context"
	"encoding/json"
	"os"
	"testing"
	"time"

	"github.com/bnema/zut/packages/provider"
)

func TestAgentRejectsEmptyPrompt(t *testing.T) {
	ag := NewAgent(nil, "model", "", nil)
	if err := ag.Prompt(context.Background(), "", nil, nil); err == nil {
		t.Fatal("empty prompt was accepted")
	}
	if got := ag.Messages(); len(got) != 0 {
		t.Fatalf("empty prompt appended %d messages", len(got))
	}
}

func TestAgentSetPromptConfigSwapsPromptAndToolsAtomically(t *testing.T) {
	oldTool := &recordingTool{}
	newTool := &recordingTool{}
	oldRegistry := Registry{"old": oldTool}
	newRegistry := Registry{"new": newTool}
	ag := NewAgent(nil, "model", "old system", oldRegistry)

	previous := ag.SetPromptConfig("new system", newRegistry)
	if previous["old"] != oldTool {
		t.Fatalf("previous registry = %#v, want old registry", previous)
	}
	system, tools := ag.PromptConfig()
	if system != "new system" {
		t.Fatalf("system prompt = %q, want new system", system)
	}
	if tools["new"] != newTool || len(tools) != 1 {
		t.Fatalf("current registry = %#v, want new registry", tools)
	}
}

func TestSessionRoundTrip(t *testing.T) {
	dir := t.TempDir()
	os.Setenv("ZUT_HOME", dir)

	sess, err := NewSession(dir, "/tmp/project", "anthropic", "claude-sonnet-4-5", "test")
	if err != nil {
		t.Fatal(err)
	}
	msg := provider.Message{
		Role: provider.RoleUser,
		Content: []provider.Content{
			provider.TextBlock{Text: "hello"},
		},
		Time: time.Now().UTC(),
	}
	if err := sess.AppendMessage(msg); err != nil {
		t.Fatal(err)
	}
	if err := sess.Close(); err != nil {
		t.Fatal(err)
	}

	reopened, msgs, err := OpenSession(sess.Path)
	if err != nil {
		t.Fatal(err)
	}
	// OpenSession returns a live append writer; close it before t.TempDir
	// runs cleanup, otherwise windows refuses to delete the open file.
	t.Cleanup(func() { _ = reopened.Close() })
	if len(msgs) != 1 {
		t.Fatalf("got %d messages", len(msgs))
	}
	tb, ok := msgs[0].Content[0].(provider.TextBlock)
	if !ok || tb.Text != "hello" {
		t.Fatalf("got %+v", msgs[0])
	}
}

func TestSessionRoundTripPreservesThoughtSignatures(t *testing.T) {
	dir := t.TempDir()
	sess, err := NewSession(dir, "/tmp/project", "google", "gemini-3-flash", "test")
	if err != nil {
		t.Fatal(err)
	}
	msg := provider.Message{
		Role: provider.RoleAssistant,
		Content: []provider.Content{
			provider.ReasoningBlock{Summary: "thinking"},
			provider.TextBlock{Text: "answer", ThoughtSignature: "text-sig"},
			provider.ImageBlock{MimeType: "image/png", Data: []byte("png"), ThoughtSignature: "image-sig"},
			provider.ToolCallBlock{
				ID:               "call-1",
				Name:             "read",
				Arguments:        []byte(`{"path":"a"}`),
				ThoughtSignature: "tool-sig",
			},
		},
	}
	if err := sess.AppendMessage(msg); err != nil {
		t.Fatal(err)
	}
	if err := sess.AppendMessage(provider.Message{
		Role: provider.RoleTool,
		Content: []provider.Content{provider.ToolResultBlock{
			CallID:  "call-1",
			Content: []provider.Content{provider.TextBlock{Text: "result"}},
		}},
	}); err != nil {
		t.Fatal(err)
	}
	if err := sess.Close(); err != nil {
		t.Fatal(err)
	}

	reopened, msgs, err := OpenSession(sess.Path)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = reopened.Close() })
	if len(msgs) != 2 || len(msgs[0].Content) != 4 {
		t.Fatalf("round trip content = %+v", msgs)
	}
	if rb, ok := msgs[0].Content[0].(provider.ReasoningBlock); !ok || rb.Summary != "thinking" {
		t.Fatalf("reasoning block = %#v", msgs[0].Content[0])
	}
	if tb, ok := msgs[0].Content[1].(provider.TextBlock); !ok || tb.ThoughtSignature != "text-sig" {
		t.Fatalf("text block = %#v", msgs[0].Content[1])
	}
	if ib, ok := msgs[0].Content[2].(provider.ImageBlock); !ok || ib.ThoughtSignature != "image-sig" {
		t.Fatalf("image block = %#v", msgs[0].Content[2])
	}
	if tc, ok := msgs[0].Content[3].(provider.ToolCallBlock); !ok || tc.ThoughtSignature != "tool-sig" {
		t.Fatalf("tool call block = %#v", msgs[0].Content[3])
	}
}

// TestNewSessionAtPathCreatesAtExplicitPath proves the subagent worker's
// session-persistence fallback works: NewSessionAtPath creates the
// file (and parent dirs) at the exact path the caller chose,
// independent of SessionsDir(root, cwd). Without this helper, the
// subagent worker's --session <path> with a non-existent path would
// fall through to NewSession and write the session under a
// different (autogenerated) name, leaving the supervisor-chosen
// path empty.
func TestNewSessionAtPathCreatesAtExplicitPath(t *testing.T) {
	dir := t.TempDir()
	want := dir + "/nested/sub/session.json"

	s, err := NewSessionAtPath(want, "/tmp/proj", "anthropic", "claude", "test")
	if err != nil {
		t.Fatalf("NewSessionAtPath: %v", err)
	}
	if s.Path != want {
		t.Errorf("Path = %q; want %q", s.Path, want)
	}
	if err := s.AppendMessage(provider.Message{
		Role:    provider.RoleUser,
		Content: []provider.Content{provider.TextBlock{Text: "hi"}},
		Time:    time.Now().UTC(),
	}); err != nil {
		t.Fatal(err)
	}
	if err := s.Close(); err != nil {
		t.Fatal(err)
	}

	// Reopen at the same path and the message must still be there.
	reopened, msgs, err := OpenSession(want)
	if err != nil {
		t.Fatalf("OpenSession at fixed path: %v", err)
	}
	t.Cleanup(func() { _ = reopened.Close() })
	if len(msgs) != 1 {
		t.Fatalf("reopen got %d msgs; want 1", len(msgs))
	}

	// A second call to NewSessionAtPath at the same path must fail
	// (O_EXCL): callers should use OpenSession to reattach to an
	// existing file.
	if _, err := NewSessionAtPath(want, "/tmp/proj", "anthropic", "claude", "test"); err == nil {
		t.Error("NewSessionAtPath on existing path returned nil; want error")
	}
}

func TestSessionExtensionStateRoundTrip(t *testing.T) {
	dir := t.TempDir()
	sess, err := NewSession(dir, "/tmp/project", "anthropic", "claude", "test")
	if err != nil {
		t.Fatal(err)
	}
	if err := sess.AppendMessage(provider.Message{
		Role:    provider.RoleUser,
		Content: []provider.Content{provider.TextBlock{Text: "prompt"}},
	}); err != nil {
		t.Fatal(err)
	}
	state := json.RawMessage(`{"phases":[{"id":"phase-1"}]}`)
	if err := sess.AppendExtensionState("tasked-phases", state); err != nil {
		t.Fatal(err)
	}
	if err := sess.Close(); err != nil {
		t.Fatal(err)
	}

	reopened, _, err := OpenSession(sess.Path)
	if err != nil {
		t.Fatal(err)
	}
	firstReopened := reopened
	t.Cleanup(func() { _ = firstReopened.Close() })
	if got := string(reopened.ExtensionState["tasked-phases"]); got != string(state) {
		t.Fatalf("extension state = %q, want %q", got, state)
	}
	if err := reopened.AppendExtensionState("tasked-phases", nil); err != nil {
		t.Fatal(err)
	}
	if _, ok := reopened.ExtensionState["tasked-phases"]; ok {
		t.Fatal("nil extension state did not clear the snapshot")
	}
	if err := reopened.Close(); err != nil {
		t.Fatal(err)
	}
	reopened, _, err = OpenSession(sess.Path)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = reopened.Close() })
	if _, ok := reopened.ExtensionState["tasked-phases"]; ok {
		t.Fatal("cleared extension state was restored after reopening")
	}
}

func TestSessionRetainsExtensionStateWithoutMessages(t *testing.T) {
	dir := t.TempDir()
	sess, err := NewSession(dir, "/tmp/project", "anthropic", "claude", "test")
	if err != nil {
		t.Fatal(err)
	}
	state := json.RawMessage(`{"version":1}`)
	if err := sess.AppendExtensionState("tasked-phases", state); err != nil {
		t.Fatal(err)
	}
	path := sess.Path
	if err := sess.Close(); err != nil {
		t.Fatal(err)
	}
	reopened, _, err := OpenSession(path)
	if err != nil {
		t.Fatal(err)
	}
	defer reopened.Close()
	if got := string(reopened.ExtensionState["tasked-phases"]); got != string(state) {
		t.Fatalf("extension state = %q, want %q", got, state)
	}
}

func TestSessionCompactHandoffRoundTripAndClear(t *testing.T) {
	sess, err := NewSession(t.TempDir(), "/tmp/project", "anthropic", "claude", "test")
	if err != nil {
		t.Fatal(err)
	}
	state := json.RawMessage(`{"version":1,"reason":"status_rescue","rescue_attempts":1}`)
	if err := sess.UpdateCompactHandoff(state); err != nil {
		t.Fatal(err)
	}
	if got := string(sess.Meta.CompactHandoff); got != string(state) {
		t.Fatalf("live compact handoff = %q, want %q", got, state)
	}
	if err := sess.Close(); err != nil {
		t.Fatal(err)
	}

	reopened, _, err := OpenSession(sess.Path)
	if err != nil {
		t.Fatal(err)
	}
	if got := string(reopened.Meta.CompactHandoff); got != string(state) {
		t.Fatalf("reopened compact handoff = %q, want %q", got, state)
	}
	if err := reopened.UpdateCompactHandoff(nil); err != nil {
		t.Fatal(err)
	}
	if err := reopened.Close(); err != nil {
		t.Fatal(err)
	}

	reopened, _, err = OpenSession(sess.Path)
	if err != nil {
		t.Fatal(err)
	}
	defer reopened.Close()
	if len(reopened.Meta.CompactHandoff) != 0 {
		t.Fatalf("cleared compact handoff = %q, want empty", reopened.Meta.CompactHandoff)
	}
}

func TestSessionGoalRoundTripAndClear(t *testing.T) {
	sess, err := NewSession(t.TempDir(), "/tmp/project", "anthropic", "claude", "test")
	if err != nil {
		t.Fatal(err)
	}
	goal := &SessionGoal{Objective: "finish the requested change", Status: GoalActive}
	if err := sess.UpdateGoal(goal); err != nil {
		t.Fatal(err)
	}
	if sess.Meta.Goal == nil || *sess.Meta.Goal != *goal {
		t.Fatalf("live goal = %#v, want %#v", sess.Meta.Goal, goal)
	}
	if err := sess.Close(); err != nil {
		t.Fatal(err)
	}

	reopened, _, err := OpenSession(sess.Path)
	if err != nil {
		t.Fatal(err)
	}
	if reopened.Meta.Goal == nil || *reopened.Meta.Goal != *goal {
		t.Fatalf("reopened goal = %#v, want %#v", reopened.Meta.Goal, goal)
	}
	if err := reopened.UpdateGoal(nil); err != nil {
		t.Fatal(err)
	}
	if err := reopened.Close(); err != nil {
		t.Fatal(err)
	}

	reopened, _, err = OpenSession(sess.Path)
	if err != nil {
		t.Fatal(err)
	}
	defer reopened.Close()
	if reopened.Meta.Goal != nil {
		t.Fatalf("cleared goal = %#v, want nil", reopened.Meta.Goal)
	}
}

func TestCostAdd(t *testing.T) {
	var c CostTracker
	c.Add(provider.Usage{InputTokens: 100, OutputTokens: 50, ReasoningTokens: 20, ReasoningTokensKnown: true, CostUSD: 0.01})
	c.Add(provider.Usage{InputTokens: 200, OutputTokens: 25, ReasoningTokens: 10, ReasoningTokensKnown: true, CostUSD: 0.02})
	if c.Total.InputTokens != 300 || c.Total.OutputTokens != 75 {
		t.Fatalf("got %+v", c.Total)
	}
	if c.Total.ReasoningTokens != 30 || !c.Total.ReasoningTokensKnown {
		t.Fatalf("got reasoning usage %+v", c.Total)
	}
	if c.Total.CostUSD < 0.0299 || c.Total.CostUSD > 0.0301 {
		t.Fatalf("got cost %v", c.Total.CostUSD)
	}
}
